parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            code_id: 'EataDevTest\Infrastructure\Doctrine\Type\CodeIdType'
            code_order_id: 'EataDevTest\Infrastructure\Doctrine\Type\CodeOrderIdType'
            code_order_line_id: 'EataDevTest\Infrastructure\Doctrine\Type\CodeOrderLineIdType'
            code_ticket_id: 'EataDevTest\Infrastructure\Doctrine\Type\CodeTicketIdType'
            code_validation_date: 'EataDevTest\Infrastructure\Doctrine\Type\CodeValidationDateType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            EataDevTest:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/doctrine/mappings'
                prefix: 'EataDevTest\Domain'
                alias: 'EataDevTest'
