EataDevTest\Domain\Order\Model\Order:
    collectionOperations:
        post:
            method: 'POST'
            path: '/order.{_format}'
            controller: 'EataDevTest\Infrastructure\Controller\PostOrder'
            defaults:
                _api_receive: false
            swagger_context:
                summary: 'Creates an Order resource.'
                parameters:
                    -
                        in: 'body'
                        name: 'body'
                        description: 'The new Order resource'
                        required: true
                        schema:
                            type: 'object'
                            title: 'Order'
                            properties:
                                purchaser:
                                    type: 'object'
                                    properties:
                                        documentId:
                                            type: 'string'
                                        email:
                                            type: 'string'
                                            format: 'email'
                                        name:
                                            type: 'string'
                                        lastName:
                                            type: 'string'
                                        zipCode:
                                            type: 'string'
                                lines:
                                    type: 'array'
                                    items:
                                        type: 'object'
                                        properties:
                                            ticketId:
                                                type: 'string'
                                            quantity:
                                                type: 'integer'
                responses:
                    201:
                        description: 'Order resource created'
                        schema:
                            type: 'object'
                            title: 'Order'
                            properties:
                                purchaser:
                                    type: 'object'
                                    properties:
                                        documentId:
                                            type: 'string'
                                        email:
                                            type: 'string'
                                            format: 'email'
                                        name:
                                            type: 'string'
                                        lastName:
                                            type: 'string'
                                        zipCode:
                                            type: 'string'
                                lines:
                                    type: 'array'
                                    items:
                                        type: 'object'
                                        properties:
                                            ticketId:
                                                type: 'string'
                                            quantity:
                                                type: 'integer'
                    400:
                        description: 'Invalid input'
                    404:
                        description: 'Resource not found'
    itemOperations: []